<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "company".
 *
 * @property int $id
 * @property int $userId
 * @property string $name
 * @property string $director_name
 * @property int $regionId
 * @property int $cityId
 * @property string $address
 * @property string $phone
 * @property string $logo
 * @property int|null $status
 * @property string|null $date
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Company extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * {@inheritdoc}
     */

    public $username;
    public $password;
    public $email;
    public $imgLogo;

    const SCENARIO_CABINET = 'cabinet';
    const SCENARIO_SIGNUP = 'signup';

    public function rules()
    {
        return [
            [['userId', 'name', 'director_name', 'regionId', 'cityId', 'address', 'phone', 'logo', 'username', 'password', 'email'], 'required'],
            [['userId', 'regionId', 'cityId', 'status'], 'integer'],
            [['date', 'created_at', 'updated_at'], 'safe'],
            [['name', 'director_name', 'address', 'logo'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 16],
            [['imgLogo'], 'file'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'userId' => Yii::t('app', 'User ID'),
            'name' => Yii::t('app', 'Name'),
            'director_name' => Yii::t('app', 'Director Name'),
            'regionId' => Yii::t('app', 'Region'),
            'cityId' => Yii::t('app', 'City'),
            'address' => Yii::t('app', 'Address'),
            'phone' => Yii::t('app', 'Phone'),
            'logo' => Yii::t('app', 'Logo'),
            'imgLogo' => Yii::t('app', 'Logo'),
            'status' => Yii::t('app', 'Status'),
            'date' => Yii::t('app', 'Date'),
            'created_at' => Yii::t('app', 'Created At'),
            'username' => Yii::t('app', 'Username'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
        ];
    }

    public function scenarios()
    {
        return [
            self::SCENARIO_SIGNUP => ['userId', 'name', 'director_name', 'regionId', 'cityId', 'address', 'phone', 'logo', 'imgLogo', 'status', 'date', 'username', 'email', 'password'],
            self::SCENARIO_CABINET => ['name', 'director_name', 'regionId', 'cityId', 'address', 'phone', 'imgLogo', 'logo'],
        ];
    }

    public function beforeSave($insert)
    {
        $this->phone = str_replace('-', '', $this->phone);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getRegion() //Regionni qaniqlash
    {
        return $this->hasOne(Region::className(), ['id' => 'regionId']);
    }

    public function getCity() //Cityni qaniqlash
    {
        return $this->hasOne(City::className(), ['id' => 'cityId']);
    }

    public function upload()
    {
        $this->logo = 'img/company/' . $this->imgLogo->baseName . '.' . $this->imgLogo->extension;

        if ($this->validate()) {
            $this->imgLogo->saveAs(Yii::getAlias('@frontend') . '/web/img/company/' . $this->imgLogo->baseName . '.' . $this->imgLogo->extension);
            return true;
        } else {
            return false;
        }
    }
}
